//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-474 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.18 at 12:12:04 AM CDT 
//

package org.hackystat.socnet.server.resource.socialmediagraph.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://hackystat-analysis-telemetry.googlecode.com/svn/trunk/xml/schema/telemetry.resource.xsd}Parameter&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://hackystat-analysis-telemetry.googlecode.com/svn/trunk/xml/schema/telemetry.resource.xsd}TelemetryStream&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref=&quot;{http://hackystat-analysis-telemetry.googlecode.com/svn/trunk/xml/schema/telemetry.resource.xsd}URI use=&quot;required&quot;&quot;/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "parameter", "telemetryStream" })
@XmlRootElement(name = "TelemetryChartData")
public class TelemetryChartData implements Serializable {

  private final static long serialVersionUID = 12343L;
  @XmlElement(name = "Parameter")
  protected List<Parameter> parameter;
  @XmlElement(name = "TelemetryStream")
  protected List<TelemetryStream> telemetryStream;
  @XmlAttribute(name = "URI", namespace = "http://hackystat-analysis-telemetry.googlecode.com/svn/trunk/xml/schema/telemetry.resource.xsd", required = true)
  protected String uri;

  /**
   * Gets the value of the parameter property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the parameter property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getParameter().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Parameter }
   * 
   * 
   */
  public List<Parameter> getParameter() {
    if (parameter == null) {
      parameter = new ArrayList<Parameter>();
    }
    return this.parameter;
  }

  public boolean isSetParameter() {
    return ((this.parameter != null) && (!this.parameter.isEmpty()));
  }

  public void unsetParameter() {
    this.parameter = null;
  }

  /**
   * Gets the value of the telemetryStream property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the telemetryStream property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getTelemetryStream().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link TelemetryStream }
   * 
   * 
   */
  public List<TelemetryStream> getTelemetryStream() {
    if (telemetryStream == null) {
      telemetryStream = new ArrayList<TelemetryStream>();
    }
    return this.telemetryStream;
  }

  public boolean isSetTelemetryStream() {
    return ((this.telemetryStream != null) && (!this.telemetryStream.isEmpty()));
  }

  public void unsetTelemetryStream() {
    this.telemetryStream = null;
  }

  /**
   * Gets the value of the uri property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getURI() {
    return uri;
  }

  /**
   * Sets the value of the uri property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setURI(String value) {
    this.uri = value;
  }

  public boolean isSetURI() {
    return (this.uri != null);
  }

}
