//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-474 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.18 at 12:12:04 AM CDT 
//

package org.hackystat.socnet.server.resource.socialmediagraph.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://hackystat-analysis-socnet.googlecode.com/svn/trunk/xml/schema/socialmediagraph.xsd}XMLRelationshipRef&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "xmlRelationshipRef" })
@XmlRootElement(name = "XMLRelationshipIndex", namespace = "http://hackystat-analysis-socnet.googlecode.com/svn/trunk/xml/schema/socialmediagraph.xsd")
public class XMLRelationshipIndex implements Serializable {

  private final static long serialVersionUID = 12343L;
  @XmlElement(name = "XMLRelationshipRef", namespace = "http://hackystat-analysis-socnet.googlecode.com/svn/trunk/xml/schema/socialmediagraph.xsd")
  protected List<XMLRelationshipRef> xmlRelationshipRef;

  /**
   * Gets the value of the xmlRelationshipRef property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the xmlRelationshipRef property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getXMLRelationshipRef().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link XMLRelationshipRef }
   * 
   * 
   */
  public List<XMLRelationshipRef> getXMLRelationshipRef() {
    if (xmlRelationshipRef == null) {
      xmlRelationshipRef = new ArrayList<XMLRelationshipRef>();
    }
    return this.xmlRelationshipRef;
  }

  public boolean isSetXMLRelationshipRef() {
    return ((this.xmlRelationshipRef != null) && (!this.xmlRelationshipRef.isEmpty()));
  }

  public void unsetXMLRelationshipRef() {
    this.xmlRelationshipRef = null;
  }

}
