//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-474 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.11 at 09:46:06 PM CDT 
//


package org.hackystat.socnet.server.resource.socialmediagraph.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}XMLRelationship" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xmlRelationship"
})
@XmlRootElement(name = "XMLRelationships")
public class XMLRelationships
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "XMLRelationship", required = true)
    protected List<XMLRelationship> xmlRelationship;

    /**
     * Gets the value of the xmlRelationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xmlRelationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXMLRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLRelationship }
     * 
     * 
     */
    public List<XMLRelationship> getXMLRelationship() {
        if (xmlRelationship == null) {
            xmlRelationship = new ArrayList<XMLRelationship>();
        }
        return this.xmlRelationship;
    }

    public boolean isSetXMLRelationship() {
        return ((this.xmlRelationship!= null)&&(!this.xmlRelationship.isEmpty()));
    }

    public void unsetXMLRelationship() {
        this.xmlRelationship = null;
    }

}
